spring:
  application:
    name: employee-reactive
  r2dbc:
    url: r2dbc:h2:mem:///employees;DB_CLOSE_DELAY=-1
  flyway:
    url: jdbc:h2:mem:employees;DB_CLOSE_DELAY=-1
    locations: classpath:db/h2/migration

